/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package requisiciones;

import BD.Conexion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Aprobaciones extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    public Conexion consultas = new Conexion();

    public Aprobaciones() {
        initComponents();
        setLocationRelativeTo(null);
        tblRequisiciones.removeAll();
        tblRequisiciones.setModel(consultas.requisicionesPorAprobar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequisiciones = new javax.swing.JTable();
        lblMenu = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JPanel();
        lblAprobar = new javax.swing.JLabel();
        btnRechazar = new javax.swing.JPanel();
        lblRechazar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRequisiciones1 = new javax.swing.JTable();
        btnAceptar1 = new javax.swing.JPanel();
        lblAprobar1 = new javax.swing.JLabel();
        btnRechazar1 = new javax.swing.JPanel();
        lblRechazar1 = new javax.swing.JLabel();
        lblMenu2 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        tblRequisiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Requisitor", "Monto", "Fecha creacion", "Detalles", "Estado", "Nivel de Aprobacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequisiciones);

        lblMenu.setBackground(new java.awt.Color(255, 255, 255));
        lblMenu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("Menu principal");
        lblMenu.setIconTextGap(7);
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(97, 212, 195));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.setLayout(null);

        lblAprobar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAprobar.setForeground(new java.awt.Color(36, 47, 65));
        lblAprobar.setText("        Aprobar");
        lblAprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAprobarMouseClicked(evt);
            }
        });
        btnAceptar.add(lblAprobar);
        lblAprobar.setBounds(100, 0, 150, 40);

        btnRechazar.setBackground(new java.awt.Color(97, 212, 195));
        btnRechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechazarMouseClicked(evt);
            }
        });
        btnRechazar.setLayout(null);

        lblRechazar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRechazar.setForeground(new java.awt.Color(36, 47, 65));
        lblRechazar.setText("        Rechazar");
        lblRechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRechazarMouseClicked(evt);
            }
        });
        btnRechazar.add(lblRechazar);
        lblRechazar.setBounds(110, 0, 150, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblMenu)
                    .addContainerGap(812, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblMenu)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        tblRequisiciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Requisitor", "Monto", "Fecha creacion", "Detalles", "Estado", "Nivel de Aprobacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRequisiciones1);

        btnAceptar1.setBackground(new java.awt.Color(97, 212, 195));
        btnAceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptar1MouseClicked(evt);
            }
        });
        btnAceptar1.setLayout(null);

        lblAprobar1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAprobar1.setForeground(new java.awt.Color(36, 47, 65));
        lblAprobar1.setText("        Aprobar");
        lblAprobar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAprobar1MouseClicked(evt);
            }
        });
        btnAceptar1.add(lblAprobar1);
        lblAprobar1.setBounds(100, 0, 150, 40);

        btnRechazar1.setBackground(new java.awt.Color(97, 212, 195));
        btnRechazar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechazar1MouseClicked(evt);
            }
        });
        btnRechazar1.setLayout(null);

        lblRechazar1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRechazar1.setForeground(new java.awt.Color(36, 47, 65));
        lblRechazar1.setText("        Rechazar");
        lblRechazar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRechazar1MouseClicked(evt);
            }
        });
        btnRechazar1.add(lblRechazar1);
        lblRechazar1.setBounds(110, 0, 150, 40);

        lblMenu2.setBackground(new java.awt.Color(255, 255, 255));
        lblMenu2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblMenu2.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/home.png"))); // NOI18N
        lblMenu2.setText("Menu principal");
        lblMenu2.setIconTextGap(7);
        lblMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenu2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRechazar1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechazar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblAprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAprobarMouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.aprobarRequisicion(i);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAprobarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.aprobarRequisicion(i);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void lblRechazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazarMouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.rechazarRequisicion(0);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRechazarMouseClicked

    private void btnRechazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechazarMouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.rechazarRequisicion(i);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRechazarMouseClicked

    private void lblAprobar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAprobar1MouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.aprobarRequisicion(i);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAprobar1MouseClicked

    private void btnAceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptar1MouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.aprobarRequisicion(i);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptar1MouseClicked

    private void lblRechazar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazar1MouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.rechazarRequisicion(0);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRechazar1MouseClicked

    private void btnRechazar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechazar1MouseClicked
        Integer i = Integer.parseInt((String) tblRequisiciones.getValueAt(tblRequisiciones.getSelectedRow(), 0));
        consultas.rechazarRequisicion(i);
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRechazar1MouseClicked

    private void lblMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenu2MouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aprobaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aprobaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aprobaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aprobaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aprobaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAceptar;
    private javax.swing.JPanel btnAceptar1;
    private javax.swing.JPanel btnRechazar;
    private javax.swing.JPanel btnRechazar1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAprobar;
    private javax.swing.JLabel lblAprobar1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenu2;
    private javax.swing.JLabel lblRechazar;
    private javax.swing.JLabel lblRechazar1;
    private javax.swing.JTable tblRequisiciones;
    private javax.swing.JTable tblRequisiciones1;
    // End of variables declaration//GEN-END:variables
}
